### ISSUE TITLE
add a member in backend w/o password doesn't work

### ISSUE THREAD

**Issue by manu37** [cmb69/register_xh#46]
In backend:
Add a member without password returns "sucess", but the member won't be listed.

Anyway: How do I add members and force them to add their password themselves? I don't want to open registration for public.

**Comment by cmb69** [comment]
> Add a member without password returns "sucess", but the member won't be listed.

That would be a bug. Either an empty password should be accepted, or an error should be raised. I tend to the latter.

> How do I add members and force them to add their password themselves? I don't want to open registration for public.

Well, you can assign them an unguessable password, but don't tell them which it is. Then they'd have to go through the password forgotten procedure. That wouldn't force them to enter an own password, but at least nobody else knows their new password.

**Comment by frase-git** [comment]
Tatsächlich wird der Member in `users.csv` angelegt, aber wirklich nicht angezeigt.

**Comment by cmb69** [comment]
Indeed, the [relevant code](https://github.com/cmb69/register_xh/blob/1.6/classes/DbService.php#L160-L162) looks rather fishy: all fields must be set, but the status field check is commented out.
