### ISSUE TITLE
Provide overview of pages showing which are protected

### ISSUE THREAD

**Issue by g7sim** [cmb69/register_xh#56]
The plugin is of course better than nothing, but it is quite cumbersome with the authorization entries in the pages.
Why don't you rewrite it in an object-oriented manner like pagemanager. Alternatively all pages could be represented in a tree or a data-table. Then assign the authorized users and groups within a mouse hover -popup. Then you would have a certain overview. This would be for a version 2.0

At the moment it would be easier for users to have a new tab beside meta  in which the owner, userrigts and groups etc. can be  chosen and saved. The Cms would then fill  the necessary php-code into the site - for a normal user a necessity ! An alternative is the hidden loading of userrights per site-id instead of insertion into the site-code.

**Comment by cmb69** [comment]
> Alternatively all pages could be represented in a tree or a data-table. Then assign the authorized users and groups within a mouse hover -popup. Then you would have a certain overview.

Interesting idea, but I don't see that for the near future for time reasons. However, having a passive overview should be viewable and makes sense to me.

> At the moment it would be easier for users to have a new tab beside meta in which the owner, userrigts and groups etc. can be chosen and saved.

Right. This is planned for a long time, see #43.
