### ISSUE TITLE
Add new member - password not hashed

### ISSUE THREAD

**Issue by manu37** [cmb69/register_xh#65]
If you add a new member, add a password and get a form validation error, the password wont be encrypted ( $oldpassword[]==$password[]). You wont get a valid password unless you change it to another.

**Comment by manu37** [comment]
[Here ](https://github.com/cmb69/register_xh/blob/97f0f0e846c73009963159eaa59763e4d9a9e35f/classes/MainAdminController.php#L157)not to check on $entryErrors should solve the issue

**Comment by cmb69** [comment]
Thanks @manu37! I shall have a look at this ASAP.

**Comment by cmb69** [comment]
> I shall have a look at this ASAP.

Embarrassing!

> [Here ](https://github.com/cmb69/register_xh/blob/97f0f0e846c73009963159eaa59763e4d9a9e35f/classes/MainAdminController.php#L157)not to check on $entryErrors should solve the issue

Spot on!
