### ISSUE TITLE
Undefined array key PluginConfig.php:86

### ISSUE THREAD

**Issue by g7sim** [cmb69/register_xh#66]
After installation under php 8.1.6 i get 4 errors (1: Undefined array key 'register' ..in.. \cmsimple\classes\PluginConfig.php:86 ;  2,3 : Trying to access array offset on value of type null ....\plugins\register_xh\index.php:26  -- and same for line 73. For the last 2 is a solution with isset, but  the undefined key needs another solution.
4. The same 'Trying to access array offset on value of type null:  happens several times in  register_xh\classes\Plugin.php (sollution with ....] ?? null): )

**Comment by cmb69** [comment]
It looks like you're using the latest released version (1.6). I haven't checked the issues, but it doesn't look like these need workarounds (`$plugin_cf['register']` is supposed to be set by the CMSimple_XH core). Anyhow, I need to roll a new release ASAP.

**Comment by cmb69** [comment]
I did a quick check with PHP 8.1.4 and Register_XH 1.6 (with CMSimple_XH 1.7.5), but couldn't detect any issues (especially the index.php:26 error does not happen for me). I'm afraid this ticket is not actionable without further feedback.

**Comment by cmb69** [comment]
Closing due to lack of feedback.
